name: Analyze Flutter code

on:
  workflow_dispatch:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'
          channel: 'stable'
      - name: prepare secrets
        run: |
          touch .env
          echo "AUTH=auth" >> .env
          echo "BASE_URL=localhost:3000" >> .env
          dart pub run build_runner clean
          dart pub run build_runner build --delete-conflicting-outputs
      - name: Analyze code
        run: flutter analyze
